markdown: kramdown
exclude: ["README.md"]

# Site settings
title: Crop video online
tag_text: Crop video online
description: Crop video online is a React-based project video editing 
url: https://crop-video-online.com

author:
  twitter: evgenity_dev
  image: img/evg-logo.png
sass:
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
facebook:
  app_id: 1106892012683561
  publisher: 1312055486
  admins: 1312055486

twitter:
  username: evgenity_dev

logo: img/preview.png

social:
  name: evgenity_dev
  links: https://twitter.com/evgenity_dev

google_analytics_id: UA-79455240-1
yandex_site_verification: 738d7f2ca0d6d72c
google_site_verification: 9HsJo2El-wIEg4gLvigL2aVAMtF1Bl7mzhgA-iWYZLg
